Expoloit fix- Adjust Values Outside Slider Bar Limits
qbcore-framework/qb-tunerchip pull request #60
Opened 2023-01-09 21:52 UTC by KamuiKody

**Describe Pull request**
With the tunerchip pulled up you can open your nui dev tools. Find the post for 'save' and change the values to anything you want. This adds a server sided check to make sure these values are what they should be.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2023-01-09 22:33 UTC, r0adra93 approved these changes
LGTM

2023-01-10 15:03 UTC, charj approved these changes
LGTM

2023-01-10 15:04 UTC, charj commented on server/main.lua
> +local Threashold = {
`Threashold` -> `Threshold`

2023-01-10 15:04 UTC, charj commented on server/main.lua
> +            if Threashold[k].min > tonumber(v) or Threashold[k].max < tonumber(v) then Chip = nil end
`Threashold` -> `Threshold`

2023-01-10 15:05 UTC, charj commented on server/main.lua
> +    DropPlayer(src, Lang:t("text.this_is_not_the_idea_is_it"))
indention

2023-01-10 15:07 UTC, charj commented on server/main.lua
> +    cb(false)
`true` has changed to `false`

is_this_the_idea?

2023-01-10 17:16 UTC, KamuiKody commented on server/main.lua
> +    cb(false)
yes though it doesnt matter because it doesnt reach that far anyway it drops the player prior.

2023-01-10 17:17 UTC, KamuiKody commented on server/main.lua
> +    DropPlayer(src, Lang:t("text.this_is_not_the_idea_is_it"))
?

2023-01-19 17:51 UTC, Z3rio requested changes

2023-01-19 17:51 UTC, Z3rio commented on server/main.lua
> +    DropPlayer(src, Lang:t("text.this_is_not_the_idea_is_it"))
This would always drop the player

2023-01-19 17:51 UTC, Z3rio commented on server/main.lua
> +    cb(false)
This always gets executed, meaning that if its true the cb will first be triggered with `true` and then `false` after it

2023-01-20 11:48 UTC, r0adra93 commented on server/main.lua
> +    cb(false)
> This always gets executed, meaning that if its true the cb will first be triggered with `true` and then `false` after it

The cb is the call back and it returns the callback.

It is just like a return on a function.

2023-01-20 16:34 UTC, Z3rio commented on server/main.lua
> +    cb(false)
> > This always gets executed, meaning that if its true the cb will first be triggered with `true` and then `false` after it
> 
> The cb is the call back and it returns the callback.
> 
> It is just like a return on a function.
> 
> Nothing runs past the cb

Incorrect actually, cb doesnt return nor stop the code in any way. It simply triggers an event and continues the code as normal.
https://github.com/qbcore-framework/qb-core/blob/main/server/events.lua#L143-L149

2023-01-20 16:36 UTC, Z3rio commented on server/main.lua
> +    cb(false)
> ```lua
> if Chip then
>     return cb(true)
> end
> ```
> 
> ?

That would pretty much work, although it isnt really ideal.
```lua
if Chip then
    cb(false)
    return
end
```

Would be more ideal

2023-01-20 18:48 UTC, KamuiKody commented
at this point i no longer care edit it yourself and merge it u have the fucking ability im out of patience with the entire developement process

2023-01-20 18:59 UTC, Z3rio approved these changes

2023-01-20 18:59 UTC, merged